### ISSUE TITLE
Ore Generation

### ISSUE THREAD

**Issue by NillerUdenDild** [NoMansMinecraft/NoMansLib#1]
Hey! First of all, thanks a lot for updating to 1.12 so quickly.

I was wondering, if the ore gen part of this lib could be moved to another mod, or be off by default?
I was a bit shocked to find out a mod I wasn't completely aware I had added, was generating ores. It seems like an odd thing to have in a library.

**Comment by TheCodedOne** [comment]
The ores are in this lib because all my mods require the materials, moving them to another mod would just mean i needed to require that mod too.

**Comment by TheCodedOne** [comment]
and really, it isnt my fault if you dont check what mods you're using and change configs, the config is in there so you can disable the ore gen.

**Comment by NillerUdenDild** [comment]
Fair enough, thanks for the quick answer.
